# Generated by Django 5.1.6 on 2025-02-09 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='current_datetime',
            new_name='created_at',
        ),
    ]
